name: Add PR comment
on:
  pull_request:
    types: [opened]
jobs:
  build:
    name: Create PR comment
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment $PR_URL --body "A New Comment Was Added to Pull Request"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
