name: Add PR comment
on:
  pull_request:
    branches:
      - main
    types: 
      - opened
      - reopened
      - synchronize
      
env:
  PR_NUMBER: ${{ github.event.number }}
  PR_URL: ${{ github.event.pull_request.html_url }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Create PR comment only on opened
        if: ${{ github.event.action == 'reopened' }}
        run: |
          gh pr comment $PR_URL --body "APP1: https://testiosoite-test-pr-${{ env.PR_NUMBER }}
          APP2: https://testiosoite2-test-pr-${{ env.PR_NUMBER }}"
          
          
