name: Add PR comment
on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
      
env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  create_comment:
    name: Create PR comment
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment $PR_URL --body "https://foobar-test-pr-${{ env.PR_NUMBER }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
