name: Add PR comment
on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
      
env:
  PR_NUMBER: ${{ github.event.number }}
  PR_URL: ${{ github.event.pull_request.html_url }}

jobs:
  create_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Create PR comment only on opened
        if: ${{ github.event.type in ['opened', 'reopened'] }}
        run: gh pr comment $PR_URL --body "https://testiosoite-test-pr-${{ env.PR_NUMBER }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
